name: Choosing Epic
favicon: null
layout_spectrum: 0.2393713255878538
typography_spectrum: 0.983609908958897
title: Choosing Epic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3161831598263234
  lightness: 0.9485553910490125
  saturation: 0.395948683610186
  rhythmicContrast: 0.9700773898512125
purpose: []
